### ISSUE TITLE
AMF Validation Profiles not running

### ISSUE THREAD

**Issue by dtsimpson2** [dtsimpson2/raml-lsp#9]
```
amfProfile = <amf.ProfileName>(<unknown>await amf.AMF.loadValidationProfile(settings.validation.rules));
validationResults = await amf.AMF.validate(model, amfProfile, amf.MessageStyles.RAML);
```

The above code in the server.ts file doesn't seem to actually run the validation profile passed in. It does still validate RAML, but when the file referenced in `settings.validation.rules` contains the following:

```
#%Validation Profile 1.0

profile: Custom

extends: RAML

violation:
  - version-constraints

validations:

  version-constraints:
    message: Version is mandatory and must be a semantic version M.m.r?
    targetClass: schema.WebAPI
    propertyConstraints:
      schema.version:
        minCount: 1
        pattern: "\d+\.\d+(\.\d+)?"
```

The it doesn't matter what the `version: ` in the root of the RAML is. It reports no errors. 

Will need to refer more to the documentation [here](https://github.com/aml-org/amf/blob/develop/documentation/validation.md) to understand why.

May also need to set up a basic test separate from the extension to do more testing.
